// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import ()

type LimbTest struct {
	ID   int32
	Img  []byte
	Info string
}

type LimbTrain struct {
	ID   int32
	Img  []byte
	Info string
}

type PerelimbTest struct {
	ID   int32
	Img  []byte
	Info string
}

type PerelimbTrain struct {
	ID   int32
	Img  []byte
	Info string
}

type User struct {
	ID       int32
	Login    string
	Password string
}
