# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.23.0
import dataclasses

@dataclasses.dataclass()
class Image:
    id: int
    img: bytes
    info: str

    def __init__(self, img, info):
        self.img = img
        self.info = info


@dataclasses.dataclass()
class User:
    id: int
    login: str
    password: str

    def __init__(self, login, password):
        self.login = login
        self.password = password
