# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.23.0
import dataclasses


@dataclasses.dataclass()
class LimbTest:
    id: int
    img: memoryview
    info: str


@dataclasses.dataclass()
class LimbTrain:
    id: int
    img: memoryview
    info: str


@dataclasses.dataclass()
class PerelimbTest:
    id: int
    img: memoryview
    info: str


@dataclasses.dataclass()
class PerelimbTrain:
    id: int
    img: memoryview
    info: str


@dataclasses.dataclass()
class User:
    id: int
    login: str
    password: str
